### ISSUE TITLE
Production error only : Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by anakin59490** [stomp-js/ng2-stompjs-angular7#15]
Hi,
I have defined module that uses ng-stomp and Angular7.
It works nice except when I build the app and deploy it in Tomcat :

![nocomment](https://user-images.githubusercontent.com/16132965/61190960-adaaa580-a6a4-11e9-9408-dd133c5fe875.jpg)

The problem is that the code in production is minified...

![PUoA6](https://user-images.githubusercontent.com/16132965/61190973-ecd8f680-a6a4-11e9-8300-1e7eda4dba5f.jpg)

but i know it happens when the module is loaded so I have comment and uncomment parts of code in order to locate the error : and it come from providers part :

Here is module :

    `import {NgModule} from '@angular/core';
    import {MaterialModule} from '../app.module';
    import {CommonModule} from '@angular/common';
    import {FormsModule, ReactiveFormsModule} from '@angular/forms';
    import {DataTablesModule} from 'angular-datatables';
    import {RouterModule} from '@angular/router';
    import {CommunicationRoutes} from './communication.routing';
    import {AlertesComponent} from './alertes/alertes.component';
    import {MediasComponent} from './medias/medias.component';
    import {ModalMediaComponent} from './medias/modal.media.component';
    import { ImageViewerModule } from 'ng2-image-viewer';
    import {WebsocketComponent} from './chat/websocket.component';
    import { InjectableRxStompConfig, RxStompService, rxStompServiceFactory } from '@stomp/ng2-stompjs';
    import {myRxStompConfig} from './chat/rx-stomp-config';
    import {NotesComponent} from './notes/notes.component';

    @NgModule({
       imports: [
          CommonModule,
          RouterModule.forChild(CommunicationRoutes),
          FormsModule,
          DataTablesModule,
          MaterialModule,
          ReactiveFormsModule,
          ImageViewerModule
      ],
    declarations: [
        AlertesComponent,
        MediasComponent,
        NotesComponent,
        WebsocketComponent,
        ModalMediaComponent
    ],
    entryComponents: [
        ModalMediaComponent
    ],
    providers: [
        {
            provide: InjectableRxStompConfig,
            useValue: myRxStompConfig
        },
        {
            provide: RxStompService,
            useFactory: rxStompServiceFactory,
            deps: [InjectableRxStompConfig]
        }
    ]
    })
     export class CommunicationModule {}`

When I comment providers part, it works

I have make a try by updating global in index.html :
    `
    <head>
        <base href='/'>

        <meta charset="utf-8" />
        <link rel="apple-touch-icon" sizes="76x76" href="./assets/img/apple-icon.png" />
        <link rel="icon" type="image/png" href="./assets/img/favicon.png" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
         <title>MyApp</title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />
         <script type="application/javascript"> var global = window; </script>
     </head>
`

but nothing changes.... How can I solve this production error ?

Thank's in advance

**Comment by kum-deepak** [comment]
This can get tricky to resolve. Based on the screenshots, the error has most probably happened earlier, the mangled code fragment is, probably, trying to format the error.

Which ng2-stompjs version are you using?

Will you please try the following to help in narrowing down the error:

- If you deploy this sample in production, do you still get the same error?
- The error is caused when you are providing these classes. However providing these classes is not necessary - you can instantiate the class directly and use it (please see the code in the factory). Please test and let me know if it works that way.

For me to help, I will need access to a version of the code that reproduces the error.

**Comment by anakin59490** [comment]
hi,
to produce the build that I deploy, i type ng build --prod --base-href /MyApp/

I use 

> "@stomp/ng2-stompjs": "7.0.0"

I have also tried ^7.2.0
this is the angular.json in order to build the prod distribution:

      "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "MyApp",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/assets",
              "src/favicon.ico"
            ],
            "styles": [
              ...
            ],
            "scripts": [
             ...
            ]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },

environement.ts:

    export const environment = {
        production: false,
        apiUrl: 'http://localhost:5000',
        wsUrl: 'localhost:5000/ws'
    };

.... is replaced by environment.prod.ts : 
     export const environment = {
         production: true,
         apiUrl: 'http://xxx.xxx.xxx.xx:8080/MyAppBackend-1.0',
         wsUrl: 'xxx.xxx.xxx.xx:8080/MyAppBackend-1.0/ws'
     }; 


>  (please see the code in the factory)

Can you please, show me the file ?

Thank's for your time

**Comment by anakin59490** [comment]
Hi,
can-it be conflict with Webpack (during buil) ?

Thx

**Comment by kum-deepak** [comment]
I thought about it a lot, not able to get much clues.

Injecting the classes is not necessary to use this library. To narrow down the issue, do not inject these classes instead create the instance where you need it. Empty your providers array. To create instance follow the below snippet:

```typescript
  const rxStompService = new RxStompService();
  rxStompService.configure(rxStompConfig);
  rxStompService.activate();
```

Also enable debug in the config so that messages are logged into the console (https://stomp-js.github.io/faqs/2019/05/20/faqs.html#p-how-do-i-enable-logging-p).

**Comment by kum-deepak** [comment]
Any further information on this?

**Comment by anakin59490** [comment]
I test asap.

Thx a lot

**Comment by anakin59490** [comment]
Hi,
"chat" functionality is placed in my "Communication" module with 2 others functionalities.
Now poviders array is empty : 

```
import {NgModule} from '@angular/core';
import {MaterialModule} from '../app.module';
import {CommonModule} from '@angular/common';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {DataTablesModule} from 'angular-datatables';
import {RouterModule} from '@angular/router';
import {CommunicationRoutes} from './communication.routing';
import {AlertesComponent} from './alertes/alertes.component';
import {MediasComponent} from './medias/medias.component';
import {ModalMediaComponent} from './medias/modal.media.component';
import { ImageViewerModule } from 'ng2-image-viewer';
import {WebsocketComponent} from './chat/websocket.component';
import {NotesComponent} from './notes/notes.component';
import {InjectableRxStompConfig, RxStompService, rxStompServiceFactory} from '@stomp/ng2-stompjs';
import {myRxStompConfig} from './chat/rx-stomp-config';

@NgModule({
    imports: [
        CommonModule,
        RouterModule.forChild(CommunicationRoutes),
        FormsModule,
        DataTablesModule,
        MaterialModule,
        ReactiveFormsModule,
        ImageViewerModule
    ],
    declarations: [
        AlertesComponent,
        MediasComponent,
        NotesComponent,
        WebsocketComponent,
        ModalMediaComponent
    ],
    entryComponents: [
        ModalMediaComponent
    ],
    providers: [
        // {
        //     provide: InjectableRxStompConfig,
        //     useValue: myRxStompConfig
        // },
        // {
        //     provide: RxStompService,
        //     useFactory: rxStompServiceFactory,
        //     deps: [InjectableRxStompConfig]
        // }
    ]
})
export class CommunicationModule {}
```
rx-stomp-config don't change:

      import { InjectableRxStompConfig } from '@stomp/ng2-stompjs';
       import {environment} from '../../../environments/environment';

     export const myRxStompConfig: InjectableRxStompConfig = {

    // Which server?
    brokerURL: 'ws://' + environment.wsUrl,

    // Headers
    // Typical keys: login, passcode, host
    connectHeaders: {
        login: 'guest',
        passcode: 'guest'
    },

    // How often to heartbeat?
    // Interval in milliseconds, set to 0 to disable
    heartbeatIncoming: 0, // Typical value 0 - disabled
    heartbeatOutgoing: 0, // Typical value 20000 - every 20 seconds

    // Wait in milliseconds before attempting auto reconnect
    // Set to 0 to disable
    // Typical value 500 (500 milli seconds)
    reconnectDelay: 2000,

    // Will log diagnostics on console
    // It can be quite verbose, not recommended in production
    // Skip this key to stop logging to console
    debug: (msg: string): void => {
        //console.log(new Date(), msg);
    }
      };



Here is my component with the new rxStompService  declaration :  
```
import {Component, OnDestroy, OnInit, ViewChild} from '@angular/core';
import {Chat} from '../../models/chat';
import {AuthService} from '../../services/auth.service';
import {Subscription} from 'rxjs';
import {MyJarviaServices} from '../../services/myjarvia.services';
import {DatatableServices} from '../../services/datatable.services';
import {DataTableDirective} from 'angular-datatables';
import {contact} from '../../record/record.routing';
import {Chatuser} from '../../models/chatuser';
import {Subject} from 'rxjs/index';
import { Message } from '@stomp/stompjs';
import {RxStompService} from '@stomp/ng2-stompjs';
import {myRxStompConfig} from './rx-stomp-config';

declare const $: any;
// const Stomp = require("stompjs/lib/stomp.js").Stomp;

@Component({
  selector: 'app-ws',
  templateUrl: './websocket.component.html',
  styleUrls: ['./websocket.component.css']
})
export class WebsocketComponent implements OnInit, OnDestroy {
    @ViewChild('dataTable') table;
    dataTable: any;
    @ViewChild(DataTableDirective) datatableElement: DataTableDirective;
    public receivedMessages: Chat[] = [];
    chat: Chat;
    message: string = "";
    chatUserList: Chatuser [] = [];
    userSelected: Chatuser = {} as Chatuser;
    dtOptions: any = {};
    loading = true;
    username: string;
    rxStompService = new RxStompService();
    dtTrigger: Subject<any> = new Subject();
    private topicSubscription: Subscription;
    constructor(private authService: AuthService,
                private myJarviaServices: MyJarviaServices,
                private datatableServices: DatatableServices
    ) {

        this.rxStompService.configure(myRxStompConfig);
        this.rxStompService.activate();
        this.username = this.authService.getCurrentUser().username;
    }
```

methods don't change :  

```
connect() {
        console.log('Connexion Serveur chat');
        this.topicSubscription = this.rxStompService.watch('/topic/myjarvia').subscribe((message: Message) => {
            console.log(message.body);
            const msgChat : Chat = JSON.parse(message.body);
            console.log(msgChat);
            this.receivedMessages.push(msgChat);
        });
    }
    onSendMessage() {
      this.chat = {} as Chat;
      this.chat.message = this.message;
      this.chat.author = this.authService.getCurrentUser().username;
      this.chat.date = this.myJarviaServices.pipe.transform(new Date(), 'yyyy-MM-dd');
      this.chat.time = this.myJarviaServices.pipe.transform(new Date(), 'HH:mm:SS');
      this.chat.idaichatter1 = this.authService.getCurrentUser().id;
      this.chat.typchatter1 = 'user';
      this.chat.idaichatter2 = this.userSelected.idaientity;
      this.chat.typchatter2 = this.userSelected.type;
      console.log(this.chat);
        // const message = `Message generated at ${new Date}`;
        this.rxStompService.publish({destination: '/api/chat', body: JSON.stringify(this.chat)});
    }
```


I hope import are correct

The problem appears when i click on one of the 3 functionalities (even if it's not "chat")
but it work's nice when i launch my app by using "npm start" command.
