### ISSUE TITLE
 has no exported member 'publishParams'. Did you mean 'IPublishParams'?

### ISSUE THREAD

**Issue by sdeering** [stomp-js/ng2-stompjs-angular7#2]
<img width="1431" alt="screen shot 2018-11-26 at 1 57 37 pm" src="https://user-images.githubusercontent.com/1787454/48992420-4971ba80-f183-11e8-9788-b82c46ababd4.png">

Did you run into this problem at all?

**Comment by kum-deepak** [comment]
Yes, this indeed has been changed to `IPublishParams`. Please let me know which documentation still reefers to `publishParams`, I will correct that.

Thanks 👍

**Comment by kum-deepak** [comment]
It was caused by `publishParams` type alias getting dropped from @stomp/stompjs@5.0.1. Added it back in @stomp/stompjs@5.0.2.

I think I need a vacation 😄

**Comment by sdeering** [comment]
haha nice one thanks for taking the time to look at this
