### ISSUE TITLE
can't find any help on watching user specific queue

### ISSUE THREAD

**Issue by loicsalou** [stomp-js/ng2-stompjs-angular7#21]
Hi, sorry to post this herer but after several attempts I still can't watch a user message queue.
I have implemented a springboot backend which provides websockets ability and an Angular8 front-end which does the following:
- send a message like "Hello" to all users connected on the backend
- send a message like "Hello again" to a specific user "admin" connected on the backend

on the frontend size I have used, so far, sockjs along with stompjs and all is working fine.

Now I'd like to use @stompjs/ng2-stompjs.
So I have replaced sockjs and stompjs with @stompjs/ng2-stompjs.
Broadcast is working correctly, but sending a message to "admin" user does not work and I can't figure out why. Message is correctly sent to the backend and I can see Spring is emitting the message to the specific queue. However nothing reaches the browser.

Is there any such example somewhere ? I have tried many watch urls ("/queue/message", "/user/queue/message", "/user/admin/queue/message"...)

thanks in advance for any help !

**Comment by kum-deepak** [comment]
Considering that you have older code that works, I will suggest the following:

- I am assuming that you were using stompjs version 2/3/4 with sockjs in your earlier code.
- Use https://stomp-js.github.io/guide/stompjs/upgrading-stompjs.html to upgrade older code to @stomp/stompjs v5 in compatibility mode using sockjs. Test the application.
- Replace sockjs with Websockets and test.
- Convert your code for @stomp-js/ng2-stomp.

Please let me know how it goes.

@stomp-js/ng2-stomp internally uses @stomp/stompjs for all actual work.
