### ISSUE TITLE
Connet RabbitMQ with virtual host

### ISSUE THREAD

**Issue by Shengjian** [stomp-js/ng2-stompjs-angular7#32]
For example:
server url: ws://127.0.0.1:15674/ws
virtual host: vmpool

I tried
ws://127.0.0.1:15674/vmpool/ws
ws://127.0.0.1/vmpool:15674/ws

and both url are failed to connect.

How do I connect RabbitMQ with virtual host

**Comment by kum-deepak** [comment]
You need to pass `host` header in `connectHeaders` in the conf.

**Comment by Shengjian** [comment]
I added the host: 'vmpool', in connectHeaders in the conf
but the status always changed  (OPEN, CLOSED CONNECTING)

**Comment by kum-deepak** [comment]
Let me try it out. Give me a couple of days.

**Comment by kum-deepak** [comment]
I did the following on my RabbitMQ instance:

```bash
$ rabbitmqctl add_vhost kreatio
$ rabbitmqctl set_permissions -p kreatio guest '.*' '.*' '.*' 
```

In this demo I added `host` to the `connectHeaders`:

```
  connectHeaders: {
    login: 'guest',
    passcode: 'guest',
    host: 'kreatio'
  }
```

The sample is working as it should.

Please check console messages to see if the broker is returning ERROR. If yes, ensure the user you are trying to connect as has appropriate permissions.

Attach the console output if you are still facing issues.
